In [1]:
import numpy as np

In [2]:
import matplotlib.pyplot as py

In [3]:
import pandas as pd

In [4]:
dataset=pd.read_csv("G:\College\Data Mining\Assignments\Mall_Customers.csv")

In [5]:
dataset

CustomerID   Genre  Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male   19                  15                      39
1             2    Male   21                  15                      81
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
5             6  Female   22                  17                      76
6             7  Female   35                  18                       6
7             8  Female   23                  18                      94
8             9    Male   64                  19                       3
9            10  Female   30                  19                      72
10           11    Male   67                  19                      14
11           12  Female   35                  19                      99
12           13  Female   58                  20                      15
13           14  Female   24                  20                      77
14           15    Male   37                  20                      13
15           16    Male   22                  20                      79
16           17  Female   35                  21                      35
17           18    Male   20                  21                      66
18           19    Male   52                  23                      29
19           20  Female   35                  23                      98
20           21    Male   35                  24                      35
21           22    Male   25                  24                      73
22           23  Female   46                  25                       5
23           24    Male   31                  25                      73
24           25  Female   54                  28                      14
25           26    Male   29                  28                      82
26           27  Female   45                  28                      32
27           28    Male   35                  28                      61
28           29  Female   40                  29                      31
29           30  Female   23                  29                      87
..          ...     ...  ...                 ...                     ...
170         171    Male   40                  87                      13
171         172    Male   28                  87                      75
172         173    Male   36                  87                      10
173         174    Male   36                  87                      92
174         175  Female   52                  88                      13
175         176  Female   30                  88                      86
176         177    Male   58                  88                      15
177         178    Male   27                  88                      69
178         179    Male   59                  93                      14
179         180    Male   35                  93                      90
180         181  Female   37                  97                      32
181         182  Female   32                  97                      86
182         183    Male   46                  98                      15
183         184  Female   29                  98                      88
184         185  Female   41                  99                      39
185         186    Male   30                  99                      97
186         187  Female   54                 101                      24
187         188    Male   28                 101                      68
188         189  Female   41                 103                      17
189         190  Female   36                 103                      85
190         191  Female   34                 103                      23
191         192  Female   32                 103                      69
192         193    Male   33                 113               

In [6]:
dataset.head()

CustomerID   Genre  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

In [7]:
x=dataset.iloc[:,:-1].values

In [8]:
y=dataset.iloc[:,4].values

In [9]:
x

array([[1, 'Male', 19, 15],
       [2, 'Male', 21, 15],
       [3, 'Female', 20, 16],
       [4, 'Female', 23, 16],
       [5, 'Female', 31, 17],
       [6, 'Female', 22, 17],
       [7, 'Female', 35, 18],
       [8, 'Female', 23, 18],
       [9, 'Male', 64, 19],
       [10, 'Female', 30, 19],
       [11, 'Male', 67, 19],
       [12, 'Female', 35, 19],
       [13, 'Female', 58, 20],
       [14, 'Female', 24, 20],
       [15, 'Male', 37, 20],
       [16, 'Male', 22, 20],
       [17, 'Female', 35, 21],
       [18, 'Male', 20, 21],
       [19, 'Male', 52, 23],
       [20, 'Female', 35, 23],
       [21, 'Male', 35, 24],
       [22, 'Male', 25, 24],
       [23, 'Female', 46, 25],
       [24, 'Male', 31, 25],
       [25, 'Female', 54, 28],
       [26, 'Male', 29, 28],
       [27, 'Female', 45, 28],
       [28, 'Male', 35, 28],
       [29, 'Female', 40, 29],
       [30, 'Female', 23, 29],
       [31, 'Male', 60, 30],
       [32, 'Female', 21, 30],
       [33, 'Male', 53, 33],
       [34, 'Mal

In [10]:
y

array([39, 81,  6, 77, 40, 76,  6, 94,  3, 72, 14, 99, 15, 77, 13, 79, 35,
       66, 29, 98, 35, 73,  5, 73, 14, 82, 32, 61, 31, 87,  4, 73,  4, 92,
       14, 81, 17, 73, 26, 75, 35, 92, 36, 61, 28, 65, 55, 47, 42, 42, 52,
       60, 54, 60, 45, 41, 50, 46, 51, 46, 56, 55, 52, 59, 51, 59, 50, 48,
       59, 47, 55, 42, 49, 56, 47, 54, 53, 48, 52, 42, 51, 55, 41, 44, 57,
       46, 58, 55, 60, 46, 55, 41, 49, 40, 42, 52, 47, 50, 42, 49, 41, 48,
       59, 55, 56, 42, 50, 46, 43, 48, 52, 54, 42, 46, 48, 50, 43, 59, 43,
       57, 56, 40, 58, 91, 29, 77, 35, 95, 11, 75,  9, 75, 34, 71,  5, 88,
        7, 73, 10, 72,  5, 93, 40, 87, 12, 97, 36, 74, 22, 90, 17, 88, 20,
       76, 16, 89,  1, 78,  1, 73, 35, 83,  5, 93, 26, 75, 20, 95, 27, 63,
       13, 75, 10, 92, 13, 86, 15, 69, 14, 90, 32, 86, 15, 88, 39, 97, 24,
       68, 17, 85, 23, 69,  8, 91, 16, 79, 28, 74, 18, 83], dtype=int64)

In [11]:
x=dataset.iloc[:,:-3].values

In [12]:
x

array([[1, 'Male'],
       [2, 'Male'],
       [3, 'Female'],
       [4, 'Female'],
       [5, 'Female'],
       [6, 'Female'],
       [7, 'Female'],
       [8, 'Female'],
       [9, 'Male'],
       [10, 'Female'],
       [11, 'Male'],
       [12, 'Female'],
       [13, 'Female'],
       [14, 'Female'],
       [15, 'Male'],
       [16, 'Male'],
       [17, 'Female'],
       [18, 'Male'],
       [19, 'Male'],
       [20, 'Female'],
       [21, 'Male'],
       [22, 'Male'],
       [23, 'Female'],
       [24, 'Male'],
       [25, 'Female'],
       [26, 'Male'],
       [27, 'Female'],
       [28, 'Male'],
       [29, 'Female'],
       [30, 'Female'],
       [31, 'Male'],
       [32, 'Female'],
       [33, 'Male'],
       [34, 'Male'],
       [35, 'Female'],
       [36, 'Female'],
       [37, 'Female'],
       [38, 'Female'],
       [39, 'Female'],
       [40, 'Female'],
       [41, 'Female'],
       [42, 'Male'],
       [43, 'Male'],
       [44, 'Female'],
       [45, 'Female'],
       [46

In [13]:
from sklearn.preprocessing import Imputer

In [14]:
imputer=Imputer(missing_values='NaN', strategy='mean',axis=0)

C:\Users\Mandovi\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [15]:
imputer=Imputer(missing_values='NaN', strategy='mean',axis=0)
imputer=imputer.fit(x[:,2:3])
x[:,2:3]=imputer.transform(x[:,2:3])

C:\Users\Mandovi\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


ValueError: Found array with 0 feature(s) (shape=(200, 0)) while a minimum of 1 is required.

In [16]:
x

array([[1, 'Male'],
       [2, 'Male'],
       [3, 'Female'],
       [4, 'Female'],
       [5, 'Female'],
       [6, 'Female'],
       [7, 'Female'],
       [8, 'Female'],
       [9, 'Male'],
       [10, 'Female'],
       [11, 'Male'],
       [12, 'Female'],
       [13, 'Female'],
       [14, 'Female'],
       [15, 'Male'],
       [16, 'Male'],
       [17, 'Female'],
       [18, 'Male'],
       [19, 'Male'],
       [20, 'Female'],
       [21, 'Male'],
       [22, 'Male'],
       [23, 'Female'],
       [24, 'Male'],
       [25, 'Female'],
       [26, 'Male'],
       [27, 'Female'],
       [28, 'Male'],
       [29, 'Female'],
       [30, 'Female'],
       [31, 'Male'],
       [32, 'Female'],
       [33, 'Male'],
       [34, 'Male'],
       [35, 'Female'],
       [36, 'Female'],
       [37, 'Female'],
       [38, 'Female'],
       [39, 'Female'],
       [40, 'Female'],
       [41, 'Female'],
       [42, 'Male'],
       [43, 'Male'],
       [44, 'Female'],
       [45, 'Female'],
       [46

In [17]:
x=dataset.iloc[:,:-1].values

In [18]:
x

array([[1, 'Male', 19, 15],
       [2, 'Male', 21, 15],
       [3, 'Female', 20, 16],
       [4, 'Female', 23, 16],
       [5, 'Female', 31, 17],
       [6, 'Female', 22, 17],
       [7, 'Female', 35, 18],
       [8, 'Female', 23, 18],
       [9, 'Male', 64, 19],
       [10, 'Female', 30, 19],
       [11, 'Male', 67, 19],
       [12, 'Female', 35, 19],
       [13, 'Female', 58, 20],
       [14, 'Female', 24, 20],
       [15, 'Male', 37, 20],
       [16, 'Male', 22, 20],
       [17, 'Female', 35, 21],
       [18, 'Male', 20, 21],
       [19, 'Male', 52, 23],
       [20, 'Female', 35, 23],
       [21, 'Male', 35, 24],
       [22, 'Male', 25, 24],
       [23, 'Female', 46, 25],
       [24, 'Male', 31, 25],
       [25, 'Female', 54, 28],
       [26, 'Male', 29, 28],
       [27, 'Female', 45, 28],
       [28, 'Male', 35, 28],
       [29, 'Female', 40, 29],
       [30, 'Female', 23, 29],
       [31, 'Male', 60, 30],
       [32, 'Female', 21, 30],
       [33, 'Male', 53, 33],
       [34, 'Mal

In [19]:
from sklearn.preprocessing import Imputer
imputer=Imputer(missing_values='NaN', strategy='mean',axis=0)
imputer=imputer.fit(x[:,2:3])
x[:,2:3]=imputer.transform(x[:,2:3])

C:\Users\Mandovi\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [20]:
from sklearn.preprocessing import impute.SimpleImputer
imputer=Imputer(missing_values='NaN', strategy='mean',axis=0)
imputer=imputer.fit(x[:,2:3])
x[:,2:3]=imputer.transform(x[:,2:3])

SyntaxError: invalid syntax (<ipython-input-20-c6a3b493ba7e>, line 1)

In [21]:
from sklearn.preprocessing import impute.SimpleImputer
imputer=SimpleImputer(missing_values='NaN', strategy='mean',axis=0)
imputer=SimpleImputer.fit(x[:,2:3])
x[:,2:3]=SimpleImputer.transform(x[:,2:3])

SyntaxError: invalid syntax (<ipython-input-21-3da60ac41c57>, line 1)

In [22]:
x

array([[1, 'Male', 19.0, 15],
       [2, 'Male', 21.0, 15],
       [3, 'Female', 20.0, 16],
       [4, 'Female', 23.0, 16],
       [5, 'Female', 31.0, 17],
       [6, 'Female', 22.0, 17],
       [7, 'Female', 35.0, 18],
       [8, 'Female', 23.0, 18],
       [9, 'Male', 64.0, 19],
       [10, 'Female', 30.0, 19],
       [11, 'Male', 67.0, 19],
       [12, 'Female', 35.0, 19],
       [13, 'Female', 58.0, 20],
       [14, 'Female', 24.0, 20],
       [15, 'Male', 37.0, 20],
       [16, 'Male', 22.0, 20],
       [17, 'Female', 35.0, 21],
       [18, 'Male', 20.0, 21],
       [19, 'Male', 52.0, 23],
       [20, 'Female', 35.0, 23],
       [21, 'Male', 35.0, 24],
       [22, 'Male', 25.0, 24],
       [23, 'Female', 46.0, 25],
       [24, 'Male', 31.0, 25],
       [25, 'Female', 54.0, 28],
       [26, 'Male', 29.0, 28],
       [27, 'Female', 45.0, 28],
       [28, 'Male', 35.0, 28],
       [29, 'Female', 40.0, 29],
       [30, 'Female', 23.0, 29],
       [31, 'Male', 60.0, 30],
       [32, 'F

In [23]:
from sklearn.preprocessing import LabelEncoder
labelencoder_x=LabelEncoder()
x[:,1]=labelencoder_x.fit_transform(x[:,1])

In [24]:
x

array([[1, 1, 19.0, 15],
       [2, 1, 21.0, 15],
       [3, 0, 20.0, 16],
       [4, 0, 23.0, 16],
       [5, 0, 31.0, 17],
       [6, 0, 22.0, 17],
       [7, 0, 35.0, 18],
       [8, 0, 23.0, 18],
       [9, 1, 64.0, 19],
       [10, 0, 30.0, 19],
       [11, 1, 67.0, 19],
       [12, 0, 35.0, 19],
       [13, 0, 58.0, 20],
       [14, 0, 24.0, 20],
       [15, 1, 37.0, 20],
       [16, 1, 22.0, 20],
       [17, 0, 35.0, 21],
       [18, 1, 20.0, 21],
       [19, 1, 52.0, 23],
       [20, 0, 35.0, 23],
       [21, 1, 35.0, 24],
       [22, 1, 25.0, 24],
       [23, 0, 46.0, 25],
       [24, 1, 31.0, 25],
       [25, 0, 54.0, 28],
       [26, 1, 29.0, 28],
       [27, 0, 45.0, 28],
       [28, 1, 35.0, 28],
       [29, 0, 40.0, 29],
       [30, 0, 23.0, 29],
       [31, 1, 60.0, 30],
       [32, 0, 21.0, 30],
       [33, 1, 53.0, 33],
       [34, 1, 18.0, 33],
       [35, 0, 49.0, 33],
       [36, 0, 21.0, 33],
       [37, 0, 42.0, 34],
       [38, 0, 30.0, 34],
       [39, 0, 36.0, 

In [25]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

ValueError: too many values to unpack (expected 3)

In [26]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [27]:
len(x_train)

160

In [28]:
len(x_test)

40

In [29]:
len(y_train)

160

In [30]:
len(y_test)

40

In [31]:
from sklearn.preprocessing import StandardScaler
sc_x= StandardScaler()
x_train=sc_x.fit_transform(x_train)
x_test=sc.x.fit_transform(x_test)

C:\Users\Mandovi\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\Mandovi\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


NameError: name 'sc' is not defined

In [32]:
from sklearn.preprocessing import StandardScaler
sc_x= StandardScaler()
x_train=sc_x.fit_transform(x_train)
x_test=sc_x.fit_transform(x_test)

C:\Users\Mandovi\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\Mandovi\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [33]:
from sklearn.preprocessing import StandardScaler
sc_x=StandardScaler()
x_train=sc_x.fit_transform(x_train)
x_test=sc_x.fit_transform(x_test)

In [34]:
len(x_train)

160

In [35]:
x_train

array([[ 6.14101752e-01,  1.16316000e+00, -1.31358807e+00,
         4.71130603e-01],
       [-5.79436487e-01, -8.59726954e-01,  3.07472996e-01,
        -4.80648393e-01],
       [-1.28151780e+00, -8.59726954e-01,  4.48434827e-01,
        -1.24207159e+00],
       [ 2.45509061e-01,  1.16316000e+00, -1.38406899e+00,
         1.28490165e-01],
       [ 1.21087087e+00, -8.59726954e-01, -1.85893416e-01,
         1.00412684e+00],
       [-6.32092586e-01, -8.59726954e-01,  1.08276307e+00,
        -5.18719553e-01],
       [-1.59745440e+00,  1.16316000e+00,  1.78757223e+00,
        -1.58471203e+00],
       [-4.21468191e-01,  1.16316000e+00, -8.90702575e-01,
        -2.52221434e-01],
       [ 3.33269225e-01, -8.59726954e-01,  8.71320323e-01,
         2.42703644e-01],
       [ 7.72070049e-01, -8.59726954e-01, -4.67817079e-01,
         5.85344083e-01],
       [-4.91676323e-01, -8.59726954e-01,  5.89396659e-01,
        -4.42577234e-01],
       [ 4.38581423e-01, -8.59726954e-01, -1.10214532e+00,
      